spring:
  application:
    name: coffee-machine

  datasource:
    url: jdbc:postgresql://localhost:5432/coffee_machine_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

  flyway:
    enabled: true
